# Site settings
title: Virtuendo
email: beatrice@virtuendo.com
description: > # this means to ignore newlines until "baseurl:"
  Conseil et accompagnement à la digitalisation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.virtuendo.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
